/**
 * 🎨 Design System Tokens for Tailwind
 * Auto-generated by Style Dictionary
 * DO NOT EDIT MANUALLY
 */

export default {
  "ds": {
    "breakpoint": {
      "sm": "640px",
      "md": "768px",
      "lg": "1024px",
      "xl": "1280px",
      "2xl": "1536px"
    },
    "color": {
      "base": {
        "white": "#ffffff",
        "black": "#000000",
        "transparent": "#00000000"
      },
      "slate": {
        "50": "#f8fafc",
        "100": "#f1f5f9",
        "200": "#e2e8f0",
        "300": "#cbd5e1",
        "400": "#94a3b8",
        "500": "#64748b",
        "600": "#475569",
        "700": "#334155",
        "800": "#1e293b",
        "900": "#0f172a",
        "950": "#020617"
      },
      "purple": {
        "50": "#faf5ff",
        "100": "#f3e8ff",
        "200": "#e9d5ff",
        "300": "#d8b4fe",
        "400": "#c084fc",
        "500": "#a855f7",
        "600": "#9333ea",
        "700": "#7e22ce",
        "800": "#6b21a8",
        "900": "#581c87",
        "950": "#3b0764"
      },
      "blue": {
        "50": "#eff6ff",
        "100": "#dbeafe",
        "200": "#bfdbfe",
        "300": "#93c5fd",
        "400": "#60a5fa",
        "500": "#3b82f6",
        "600": "#2563eb",
        "700": "#1d4ed8",
        "800": "#1e40af",
        "900": "#1e3a8a",
        "950": "#172554"
      },
      "green": {
        "50": "#f0fdf4",
        "100": "#dcfce7",
        "200": "#bbf7d0",
        "300": "#86efac",
        "400": "#4ade80",
        "500": "#22c55e",
        "600": "#16a34a",
        "700": "#15803d",
        "800": "#166534",
        "900": "#14532d"
      },
      "red": {
        "50": "#fef2f2",
        "100": "#fee2e2",
        "200": "#fecaca",
        "300": "#fca5a5",
        "400": "#f87171",
        "500": "#ef4444",
        "600": "#dc2626",
        "700": "#b91c1c",
        "800": "#991b1b",
        "900": "#7f1d1d"
      },
      "orange": {
        "50": "#fff7ed",
        "100": "#ffedd5",
        "200": "#fed7aa",
        "300": "#fdba74",
        "400": "#fb923c",
        "500": "#f97316",
        "600": "#ea580c",
        "700": "#c2410c",
        "800": "#9a3412",
        "900": "#7c2d12"
      },
      "teal": {
        "50": "#f0fdfa",
        "100": "#ccfbf1",
        "200": "#99f6e4",
        "300": "#5eead4",
        "400": "#2dd4bf",
        "500": "#14b8a6",
        "600": "#0d9488",
        "700": "#0f766e",
        "800": "#115e59",
        "900": "#134e4a"
      },
      "foreground": "#1d1b20",
      "muted-foreground": "#49454f",
      "background": "#fef7ff",
      "card": "#f3edf7",
      "card-foreground": "#1d1b20",
      "popover": "#fef7ff",
      "popover-foreground": "#1d1b20",
      "muted": "#e7e0ec",
      "accent": "#e8def8",
      "accent-foreground": "#1d192b",
      "border": "#e0e0e0",
      "input": "#dadce0",
      "ring": "#1976d2",
      "primary": "#1976d2",
      "primary-foreground": "#ffffff",
      "secondary": "#00897b",
      "secondary-foreground": "#ffffff",
      "destructive": "#d32f2f",
      "destructive-foreground": "#ffffff",
      "success": "#388e3c",
      "success-foreground": "#ffffff",
      "warning": "#f57c00",
      "warning-foreground": "#ffffff",
      "info": "#0288d1",
      "info-foreground": "#ffffff"
    },
    "motion": {
      "duration": {
        "instant": "0ms",
        "fast": "100ms",
        "normal": "200ms",
        "slow": "300ms",
        "slower": "500ms"
      },
      "easing": {
        "linear": "linear",
        "in": "cubic-bezier(0.4, 0, 1, 1)",
        "out": "cubic-bezier(0, 0, 0.2, 1)",
        "in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
        "standard": "cubic-bezier(0.4, 0, 0.2, 1)",
        "bounce": "cubic-bezier(0.68, -0.55, 0.265, 1.55)"
      }
    },
    "opacity": {
      "0": "0",
      "5": "0.05",
      "10": "0.1",
      "20": "0.2",
      "30": "0.3",
      "40": "0.4",
      "50": "0.5",
      "60": "0.6",
      "70": "0.7",
      "80": "0.8",
      "90": "0.9",
      "95": "0.95",
      "100": "1"
    },
    "radius": {
      "none": "0px",
      "xs": "4px",
      "sm": "8px",
      "base": "12px",
      "md": "16px",
      "lg": "20px",
      "xl": "28px",
      "2xl": "28px",
      "3xl": "28px",
      "full": "9999px"
    },
    "shadow": {
      "none": "none",
      "xs": "0 1px 2px 0 rgba(0, 0, 0, 0.03)",
      "sm": "0 1px 3px 0 rgba(0, 0, 0, 0.08), 0 1px 2px -1px rgba(0, 0, 0, 0.08)",
      "base": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
      "md": "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.04)",
      "lg": "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)",
      "xl": "0 20px 25px -5px rgba(0, 0, 0, 0.08), 0 8px 10px -6px rgba(0, 0, 0, 0.04)",
      "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.15)",
      "inner": "inset 0 2px 4px 0 rgba(0, 0, 0, 0.04)",
      "glow": "0 0 0 3px rgba(168, 85, 247, 0.1)"
    },
    "spacing": {
      "0": "0px",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "7": "28px",
      "8": "32px",
      "9": "36px",
      "10": "40px",
      "11": "44px",
      "12": "48px",
      "14": "56px",
      "16": "64px",
      "20": "80px",
      "24": "96px",
      "28": "112px",
      "32": "128px",
      "36": "144px",
      "40": "160px",
      "48": "192px",
      "56": "224px",
      "64": "256px",
      "component": {
        "xs": "4px",
        "sm": "8px",
        "md": "12px",
        "lg": "16px",
        "xl": "24px"
      },
      "layout": {
        "xs": "16px",
        "sm": "24px",
        "md": "32px",
        "lg": "48px",
        "xl": "64px",
        "2xl": "96px",
        "3xl": "128px"
      },
      "section": {
        "xs": "48px",
        "sm": "64px",
        "md": "80px",
        "lg": "96px",
        "xl": "128px",
        "2xl": "160px"
      },
      "container": {
        "padding": "16px",
        "padding-md": "24px",
        "padding-lg": "32px"
      }
    },
    "typography": {
      "font-family": {
        "sans": "'Roboto', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        "mono": "'Roboto Mono', 'Courier New', monospace"
      },
      "font-size": {
        "xs": "11px",
        "sm": "12px",
        "base": "14px",
        "lg": "16px",
        "xl": "22px",
        "2xl": "24px",
        "3xl": "28px",
        "4xl": "32px",
        "5xl": "45px",
        "6xl": "57px",
        "7xl": "64px"
      },
      "font-weight": {
        "thin": "100",
        "light": "300",
        "regular": "400",
        "medium": "500",
        "semibold": "600",
        "bold": "700",
        "extrabold": "800",
        "black": "900"
      },
      "line-height": {
        "none": "1",
        "tight": "1.25",
        "snug": "1.33",
        "normal": "1.43",
        "relaxed": "1.5",
        "loose": "1.6"
      },
      "letter-spacing": {
        "tighter": "-0.02em",
        "tight": "0em",
        "normal": "0.01em",
        "wide": "0.02em",
        "wider": "0.03em",
        "widest": "0.05em"
      },
      "heading": {
        "h1": {
          "font-size": "45px",
          "font-weight": "700",
          "line-height": "1.25",
          "letter-spacing": "0em"
        },
        "h2": {
          "font-size": "32px",
          "font-weight": "700",
          "line-height": "1.25",
          "letter-spacing": "0em"
        },
        "h3": {
          "font-size": "28px",
          "font-weight": "600",
          "line-height": "1.33",
          "letter-spacing": "0.01em"
        },
        "h4": {
          "font-size": "24px",
          "font-weight": "600",
          "line-height": "1.33",
          "letter-spacing": "0.01em"
        },
        "h5": {
          "font-size": "22px",
          "font-weight": "600",
          "line-height": "1.43",
          "letter-spacing": "0.01em"
        },
        "h6": {
          "font-size": "16px",
          "font-weight": "600",
          "line-height": "1.43",
          "letter-spacing": "0.01em"
        }
      },
      "body": {
        "xs": {
          "font-size": "11px",
          "font-weight": "400",
          "line-height": "1.43"
        },
        "sm": {
          "font-size": "12px",
          "font-weight": "400",
          "line-height": "1.43"
        },
        "base": {
          "font-size": "14px",
          "font-weight": "400",
          "line-height": "1.43"
        },
        "lg": {
          "font-size": "16px",
          "font-weight": "400",
          "line-height": "1.5"
        }
      },
      "label": {
        "sm": {
          "font-size": "11px",
          "font-weight": "500",
          "line-height": "1.25",
          "letter-spacing": "0.02em"
        },
        "base": {
          "font-size": "12px",
          "font-weight": "500",
          "line-height": "1.25",
          "letter-spacing": "0.02em"
        }
      },
      "code": {
        "font-family": "'Roboto Mono', 'Courier New', monospace",
        "font-size": "0.875em"
      }
    },
    "z-index": {
      "hide": "-1",
      "base": "0",
      "dropdown": "1000",
      "sticky": "1100",
      "fixed": "1200",
      "overlay": "1300",
      "modal": "1400",
      "popover": "1500",
      "tooltip": "1600"
    },
    "component": {
      "button": {
        "padding-x": "16px",
        "padding-y": "12px",
        "radius": "16px",
        "font-size": "12px",
        "font-weight": "500",
        "height-sm": "2rem",
        "height-md": "2.5rem",
        "height-lg": "3rem"
      },
      "input": {
        "padding-x": "12px",
        "padding-y": "8px",
        "radius": "16px",
        "font-size": "12px",
        "height": "2.5rem",
        "border-width": "1px"
      },
      "card": {
        "padding": "24px",
        "radius": "20px",
        "shadow": "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.04)",
        "border-width": "1px"
      },
      "avatar": {
        "size-xs": "1.5rem",
        "size-sm": "2rem",
        "size-md": "2.5rem",
        "size-lg": "3rem",
        "size-xl": "4rem",
        "radius": "9999px"
      },
      "badge": {
        "padding-x": "8px",
        "padding-y": "4px",
        "radius": "9999px",
        "font-size": "11px",
        "font-weight": "500"
      },
      "modal": {
        "padding": "48px",
        "radius": "28px",
        "shadow": "0 25px 50px -12px rgba(0, 0, 0, 0.15)",
        "max-width": "32rem"
      },
      "tooltip": {
        "padding-x": "12px",
        "padding-y": "8px",
        "radius": "16px",
        "font-size": "11px",
        "shadow": "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)"
      }
    },
    "effect": {
      "elevation": {
        "0": "none",
        "1": "0 1px 2px 0 rgba(0, 0, 0, 0.03)",
        "2": "0 1px 3px 0 rgba(0, 0, 0, 0.08), 0 1px 2px -1px rgba(0, 0, 0, 0.08)",
        "3": "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.04)",
        "4": "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)",
        "5": "0 20px 25px -5px rgba(0, 0, 0, 0.08), 0 8px 10px -6px rgba(0, 0, 0, 0.04)",
        "6": "0 25px 50px -12px rgba(0, 0, 0, 0.15)"
      },
      "focus": {
        "ring-color": "#1976d2",
        "ring-width": "2px",
        "ring-offset": "2px"
      },
      "interaction": {
        "transition": "all 200ms cubic-bezier(0.4, 0, 0.2, 1)",
        "transition-fast": "all 100ms cubic-bezier(0.4, 0, 0.2, 1)",
        "transition-slow": "all 300ms cubic-bezier(0.4, 0, 0.2, 1)"
      }
    }
  }
}
